### ISSUE TITLE
有问题请教

### ISSUE THREAD

**Issue by zyannan** [chocovon/thiefbook-js#2]
兄弟在吗，方便留跟联系方式吗，你的Debug Variable Extractor，有一些问题请教

**Comment by chocovon** [comment]
base64: Y2hvY292b24yMzNAZ21haWwuY29t

**Comment by zyannan** [comment]
之前因为Debug Variable Extractor有的实体里提取json，提取不出来，可能是json解析有问题，想着如何能优化一下，后来发现可以直接改Customize Data Views里面可以改，就在那里加了fastjson的解析，暂时是满足需求了
