### ISSUE TITLE
老哥有点小问题

### ISSUE THREAD

**Issue by BogDock** [chocovon/thiefbook-js#3]
![bug](https://github.com/chocovon/thiefbook-js/assets/118803538/db6de1bb-160f-467e-93c3-db1e05bd7c3d)
这个文字会叠在一起，吞掉很多文字，然后就是一大片空白完全看不到

**Comment by chocovon** [comment]
感觉像是文件里的换行符导致的，可以提供一下文件样本吗？

**Comment by BogDock** [comment]
[直播算命粉丝全修仙了免费阅读-唐三木-免费小说全文-作者-神持钥本尊作品-七猫中文网.txt](https://github.com/chocovon/thiefbook-js/files/13365068/-.-.-.-.-.txt)
用的油猴插件怠惰下载器下载的txt

**Comment by chocovon** [comment]
修复了

**Comment by BogDock** [comment]
谢谢老哥

**Comment by BogDock** [comment]
![AAAA](https://github.com/chocovon/thiefbook-js/assets/118803538/dc43fb64-f04f-4be3-8c98-4ec572c5f9c3)
这个脚本也是老哥你弄的吗

**Comment by chocovon** [comment]
> ![AAAA](https://user-images.githubusercontent.com/118803538/283287151-dc43fb64-f04f-4be3-8c98-4ec572c5f9c3.PNG) 这个脚本也是老哥你弄的吗

不是，我的在主页里
